'use client'

import { createContext, useContext, useState, useEffect, ReactNode } from 'react'
import { useAuth } from '@/lib/auth-context'

export interface WhiteLabelConfig {
  agencyName: string
  agencyLogo: string | null        // base64 or URL
  agencyUrl: string
  accentColor: string              // hex
  reportFooter: string 
  preparedBy: string 
  clientName: string 
}


const defaults: WhiteLabelConfig = {
  agencyName: 'OUTAudits',
  agencyLogo: null,
  agencyUrl: 'https://outaudits.com',
  accentColor: '#0075FF',
  // reportFooter: 'Confidential — prepared exclusively for the client named above.',
  reportFooter: 'Report generated by OUTAudits — fast website audits and seo tools.',
  preparedBy: '',
  clientName: '',
}

interface WhiteLabelContextType {
  config: WhiteLabelConfig
  setConfig: (c: Partial<WhiteLabelConfig>) => void,
}

const WhiteLabelContext = createContext<WhiteLabelContextType>({
  config: defaults,
  setConfig: () => {},
})

export function WhiteLabelProvider({ children }: { children: ReactNode }) {
  const { user } = useAuth()
  const [config, setConfigState] = useState<WhiteLabelConfig>(() => {
    if (typeof window !== 'undefined') {
      try {
        const saved = localStorage.getItem('wl_config')
        if (saved) return { ...defaults, ...JSON.parse(saved) }
      } catch {}
    }
    return defaults
  })

  const [initialized, setInitialized] = useState(false)

  // Initialize config from database on user load
  useEffect(() => {
    if (user && !initialized) {
      const dbDefaults: Partial<WhiteLabelConfig> = {
        agencyName: user.agency_name || defaults.agencyName,
        agencyLogo: user.agency_logo || defaults.agencyLogo,
        agencyUrl: user.agency_url || defaults.agencyUrl,
        accentColor: user.accent_color || defaults.accentColor,
      }
      setConfigState(prev => ({ ...prev, ...dbDefaults }))
      if (typeof window !== 'undefined') {
        localStorage.setItem('wl_config', JSON.stringify({ ...config, ...dbDefaults }))
      }
      setInitialized(true)
    }
  }, [user, initialized])

  const setConfig = (partial: Partial<WhiteLabelConfig>) => {
    setConfigState(prev => {
      const next = { ...prev, ...partial }
      if (typeof window !== 'undefined') {
        localStorage.setItem('wl_config', JSON.stringify(next))
        // Save to database
        saveWhiteLabelToDatabase(next)
      }
      return next
    })
  }

  return (
    <WhiteLabelContext.Provider value={{ config, setConfig }}>
      {children}
    </WhiteLabelContext.Provider>
  )
}

// Helper function to save to database
export async function saveWhiteLabelToDatabase(config: any) {
  try {
    const token = localStorage.getItem('access_token')
    if (!token) return
    
    await fetch(`${process.env.NEXT_PUBLIC_API_URL}/auth/me`, {
      method: 'PATCH',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${token}`
      },
      body: JSON.stringify({
        agency_name: config.agencyName,
        agency_logo: config.agencyLogo,
        agency_url: config.agencyUrl,
        accent_color: config.accentColor,
      })
    })
  } catch (error) {
    console.error('Failed to save white-label config to database:', error)
  }
}

export const useWhiteLabel = () => useContext(WhiteLabelContext)